### ISSUE TITLE
vsce not listed as a dependency

### ISSUE THREAD

**Issue by GufNZ** [SogoCZE/Jails#10]
Trying to setup Jails for the first time, and ran into not having vsce installed.
Installed -g manually and everything worked.  Just figured it should be in the readme somewhere...

**Comment by SogoCZE** [comment]
Thanks! I've added a step to install the `vsce`: https://github.com/SogoCZE/Jails/commit/6806b4b272b2a544fb31bb50ec137ab022a9d88a.
