### ISSUE TITLE
qol: TODO Board

### ISSUE THREAD

**Issue by ArjixWasTaken** [SogoCZE/Jails#14]
A TODO board would be nice, GitHub calls them "Projects", you could also just use a markdown file

For example:

---

#### TODO
- smth smth

#### Doing
- Add support for xyz

#### Done
- Merge Raphael's fork (#1)

---

Communicating what is being worked on, and what is not being worked on, would help a lot to manage contributions.
And it makes it easier to find things to work on.

**Comment by ArjixWasTaken** [comment]
That way, you will also have a "bird-eye" view of how much of the LSP spec has been implemented.

**Comment by ArjixWasTaken** [comment]
PS: If you choose to have markdown for the TODO, I recommend having it in a pinned issue, that way you don't pollute the repository with commits to edit the TODO list, and you only have to refer to the pinned issue from the readme.

**Comment by SogoCZE** [comment]
Hello,

I added basic project and filled in some TODO's.

https://github.com/users/SogoCZE/projects/1

Thanks for suggestion.
