### ISSUE TITLE
Opening a #string immediately crashes the server

### ISSUE THREAD

**Issue by peter-slattery** [SogoCZE/Jails#17]
## To Reproduce

1. In a jai project, create a function
2. In the function, write `data := #string DONE`

## Observed Behavior

Part way through writing the line in step 2, I see the error "Connection to server got closed. Server will not be restarted". (see screenshot)

## Expected Behavior

The rest of the file would be treated like part of the #string until a closing DONE token is found. The server would not crash.

**Comment by SogoCZE** [comment]
Thank you for reporting this bug, unfortunately I am unable to replicate this bug. Can you send me the exact piece of code that should replicate this?

**Comment by peter-slattery** [comment]
Hm, yea I'm not able to repro it anymore (sorry, I didn't get notified about this for some reason). I'll keep trying and submit a full case when I get it to break.

**Comment by SogoCZE** [comment]
I will close this issue for the time being. Feel free to reopen it if you replicate it again. Thanks!
