### ISSUE TITLE
Error while resolving Jai path on linux

### ISSUE THREAD

**Issue by TatriX** [SogoCZE/Jails#18]
Hi!
On [linux](https://man7.org/linux/man-pages/man1/whereis.1.html) `whereis` doesn't support `-q` flag.
So I'm getting an error:
```
Error while resolving Jai path ...
```
Removing the flag from `run_command` seems to resolve the issue.

Thanks :)

**Comment by SogoCZE** [comment]
This should be now fixed. Thanks!
