### ISSUE TITLE
Expressions for array indices are not parsed correctly

### ISSUE THREAD

**Issue by danielmaciel** [SogoCZE/Jails#24]
Hi,

I have tried to use Jails but it spits out a bunch of errors.
A few of them are related to array index expressions. For instance `foo[a^1]` or `foo[-1]`. Also `foo[0x4000]` doesn't work, it thinks `0x4000` is an identifier
Those fail to parse.

**Comment by SogoCZE** [comment]
This is probably related to this issues in the parser https://github.com/SogoCZE/jai_parser/issues/8.
