### ISSUE TITLE
Unknown directives

### ISSUE THREAD

**Issue by danielmaciel** [SogoCZE/Jails#25]
Hi, 

I have tried to use Jails, and it spits out a bunch of errors.
A few of them are regarding unknown directives.
`#no_abc` `#type_info_none` `#specified` are a few of those.

**Comment by SogoCZE** [comment]
Hm, this seems odd as we are familiar with those directives in the parser. It appears that the parser encountered them in unexpected places. In what context does this occur?

**Comment by danielmaciel** [comment]
MyEnum :: enum_flags @Shader s32 #specified { ... }

while cursor < tl.first_index + tl.num_indices #no_abc { ... }

MyArray :: struct(T: Type, Alignment: s32 = 16) #type_info_none { ... }
