### ISSUE TITLE
Jails compiles my program on save.

### ISSUE THREAD

**Issue by xThuby** [SogoCZE/Jails#30]
Not quite sure if this is an intended feature, if so it would be nice to be able to turn if off. But it seems like saving the file that I'm editing causes the whole program to compile and output a new executable as if I ran my build command in the terminal.

I've set this up using neovim on MacOS, I've got the following config for the LSP
in: `~/.config/nvim/after/ftplugin/jai.lua`
```lua
vim.lsp.start({
    name = "jai",
    cmd = { "jails" },
    root_dir = vim.fn.getcwd(),
})

```
Repro:
Create a project with a basic `first.jai`, `src/` dir, and specify `first.jai` to build the program to `out/`
Open some file like `src/main.jai`
Edit code & save changes
Find that there's now an `out/` dir with a fresh executable file.

**Comment by Mupu** [comment]
It only outputs a new binary if you use your own metaprogram, in that case you should use disable the output on your own, by combining "JAILS_DIAGNOSTICS_BUILD " with "#exists" to detect if it is build by the lsp.

**Comment by SogoCZE** [comment]
Jails use compiler runs to report errors to the editor. As @Mupu already described if you use a custom metaprogram you need to set no output when running from Jails (`#exists(JAILS_DIAGNOSTICS_BUILD)`).

**Comment by Mupu** [comment]
Would be a good idea, indeed. It's a relatively new feature since it's based on '#exists' and you're not the first one to ask :)
